### ISSUE TITLE
False positive matches

### ISSUE THREAD

**Issue by iandunn** [runcommand/find-unused-themes#5]
I get a lot of false-positives when running this. For example:

```
> wp find-unused-themes
Checking https://wordcamp.dev/ for unused themes...
Checking https://central.wordcamp.dev/ for unused themes...
Checking https://plan.wordcamp.dev/ for unused themes...
// [etc]
+---------------+---------+
| name          | version |
+---------------+---------+
// more
| plan          | 0.1     |
// more
+---------------+---------+
```

```
> wp theme list --url=https://plan.wordcamp.dev
+-----------------------+----------+--------+---------+---------+
| name                  | status   | update | version | enabled |
+-----------------------+----------+--------+---------+---------+
// more inactive
| plan                  | active   | none   | 0.1     | site    |
// more inactive
| twentytwelve          | parent   | none   | 2.2     | network |
// more inactive
+-----------------------+----------+--------+---------+---------+
```

I added some debugging output, and it looks like the result of `WP_CLI::launch_self( 'theme list' [...] )` is incorrect. It reports that the `plan` theme is `inactive` on `plan.wordcamp.dev`. So, it seems like all the logic inside this command is correct, but perhaps there's something wrong with the way `theme list` is being called? 

Maybe the `url` parameter in the `launch_self` command isn't being used, because `theme list` is called with `launch_self` (vs something like `run_command`), and it's reusing the initial `--url` parameter from the `wp find-unused-themes` call (which, in this case, defaults to `central.wordcamp.dev` via `wp-cli.yml`)?

**Comment by danielbachhuber** [comment]
> Maybe the url parameter in the `launch_self` command isn't being used, because theme list is called with `launch_self` (vs something like `run_command`), and it's reusing the initial `--url` parameter from the `wp find-unused-themes` call (which, in this case, defaults to `central.wordcamp.dev` via `wp-cli.yml`)?

This hypothesis makes sense to me.

I was able to reproduce the issue in my local `vip.dev` multisite instance. Switching to use `WP_CLI::runcommand()` fixed the issue for me.

**Comment by iandunn** [comment]
I haven't had time to fully test this yet, but it appears to be working for me too. Thanks!
